on : push
jobs : 
      first-job : 
          runs-on : ubuntu-latest
          steps :
                - run : node --version
      second-job :
          runs-on : macos-latest
          steps : 
                - run : npm --version